export const basicYaks = [
  "i'm hornyyyy",
  "we finally have 3 starbucks in verm!",
  "Where's the best place to get a fake? Asking for a friend",
  "UPD is handing out tickets",
  "he's a 10 but he's a business major: 🚩🚩",
  "My RA is so fine",
  "*ironic comment about Eric Smith*",
  "Good morning Yotes, here's a weather report -xox weather boy",
  "Where's the 🍃 plug?",
  "hmu if you want me to do your homework",
  "anyone down to netflix and chill?",
  "UPD here, please behave this semester :)",
  "I CAN'T FIND ANY PARKING AHHHH",
  "pov: its the second day and im hungover",
  "best sorority?",
  "my neighbor has a dump truck, how do I ask her to smash?",
  "men with glasses 🤤",
  "where's the love for tall girls?",
  "My roommates have so many bottles of wipes, can I evict them?",
  "I'm officially done with blonde girls. Time to date blonde men.",
  "*yak copied from nationwide hot but nobody cares*",
  "made by @jeffrey.hugh",
  "they took coyote crazy trevor out back and shot him",
  "I heard the TKEs all got monkeypox",
  "psa: professors are on yikyak",
  "greek life is just paying $1000 for friends w a sprinkle of leadership",
  "I hate narps",
  "upvote to manifest a 4.0 this semester",
  "upvote if you have a pulse, tryna prove a point",
  "what time does the welly open?",
  "I'm bored",
  "women need a time in the welly when there are no men 💅",
];

export const buttonYaks = [
  "WHO PUSHED THE BUTTON??",
  "I swear I'm going to run over the next person to push the button",
  "Why are the freshmen always pushing the button?",
  "FYI, Charlie Coyote eats the flesh of those who push the button",
  "stop. pushing. the. button.",
  "😡😡😡😡😡😡",
  "ppl who push the button <<<<",
  "PSA: Don't push the button or you'll be taken out back and shot",
  "UPD here, why did you push the button?",
  "*angry message about pushing the button*",
];
